### ISSUE TITLE
@jsonforms/angular doesn't work in angular 15?

### ISSUE THREAD

**Issue by JuanManitta** [eclipsesource/jsonforms-angular-seed#74]
You guys think in upgrade to angular >14?

**Comment by Prasannajaga** [comment]
Hi Juan can you please explain what is the issue breifly? So that I can help you with my knowledge

**Comment by mrkhan** [comment]
Hi Prasannajaga, Could you explain how to use @jsonforms/angular with angular 16 ?

**Comment by JuanManitta** [comment]
Yes, thats the problem, @jsonforms/angular last version doesn't support angular >14. I have a project in Angular 15.2 and i really want to use jsonforms

**Comment by Prasannajaga** [comment]
understood Juan. I got the point. will work on it and update you soon

**Comment by Prasannajaga** [comment]
![image](https://github.com/eclipsesource/jsonforms-angular-seed/assets/123716600/e97d2ec4-1682-4b2a-a8b7-cc285ac3d080)

Hi Juan I'm facing this error when I run this have any idea?

**Comment by mrkhan** [comment]
Hi Juan, I switched to [formly](https://formly.dev/docs/examples/advanced/json-schema/), especially for JSON schema. It works fine with Angular 16 too.

**Comment by sdirix** [comment]
Hi! This is just the example repo of JSON Forms. You can find the issues for updating to Angular 15+ in the main repository, see

- https://github.com/eclipsesource/jsonforms/issues/2138
- https://github.com/eclipsesource/jsonforms/issues/2085
- https://github.com/eclipsesource/jsonforms/issues/1546

For simple questions instead of bugs/feature requests you can also check our [forum](https://jsonforms.discourse.group/), see for example this [Angular question](https://jsonforms.discourse.group/t/any-timeline-angular-16-json-form-support/1765/2).

**Comment by iamraj0811** [comment]
Hi
My project is using jsonforms/angular: 3.0.0
jsonforms/angular-material: 3.0.0
jsonforms/core; 3.0.0

I have changed angular version from 14 to 16 so now on npm install it is giving broken dependency error and is advising to use --force.
I don't want force to be used. How to resolve this issue.
